### ISSUE TITLE
Duration data

### ISSUE THREAD

**Issue by Its-Just-Nans** [We-Gold/gpxjs#11]
Hello

Nice package but I have a question about duration:

Is there any duration data exposed in the GPX ?
like
- total duration
- moving duration
- cumulativeDuration (I see `distance.cumulative` so why not)

Thanks

**Comment by We-Gold** [comment]
I don't believe so. The time data is parsed, but no duration information is calculated from that data.

This could be implemented similarly to distance, elevation, and slope data (e.g. the `calculateDistance` function in _math_helpers_).

Feel free to create a PR if you want to implement this feature.
