### ISSUE TITLE
Export math_helpers.ts

### ISSUE THREAD

**Issue by Its-Just-Nans** [We-Gold/gpxjs#13]
Hi

Could we export all the functions of `math_helpers.ts` ?

That way, we can use these functions without parsing again a gpx

Use case:
- I parse my gpx with default options
- My movingTime is not correct (example: I do a slow activity and the threshold is too high)
- I want to recalculate the duration

currently i can't because functions are not exported

A `export * from "./math_helpers"` in `index.ts` should be enough I guess ?

**Comment by We-Gold** [comment]
I like the idea of exposing more statistics calculations to the user, but this is not the most user-friendly way. The _math_helpers_ functions are written to be called in `parseGPX`, so they would be challenging for a new user to use outside of that context. It would be interesting to make a wrapper around each one that allows them to take as input a ParsedGPX object and recalculate the correct values. 

I'm not sure the best way to implement that, or which way would be easiest for the end user, but I think that approach would be more user-friendly than just exposing the methods as-is.
