### ISSUE TITLE
Heart rate and power

### ISSUE THREAD

**Issue by matthiaswuyts** [We-Gold/gpxjs#2]
Hi,

Could it be possible to add heartrate and power to the package?

Thanks

**Comment by We-Gold** [comment]
The library currently supports extensions, so if heart rate or power are included as extensions, they should be parsed. Are you dealing with a different GPX format that includes heart rate and power differently?

**Comment by matthiaswuyts** [comment]
> The library currently supports extensions, so if heart rate or power are included as extensions, they should be parsed. Are you dealing with a different GPX format that includes heart rate and power differently?

No thanks for telling me
