### ISSUE TITLE
Could not find a declaration file for module '@we-gold/gpxjs'

### ISSUE THREAD

**Issue by fabalexsie** [We-Gold/gpxjs#6]
Hi,
when using your package with typescript in nodejs, I get the following error:

> Could not find a declaration file for module '@we-gold/gpxjs'. '/workspaces/basic-bun/node_modules/@we-gold/gpxjs/dist/gpxjs.js' implicitly has an 'any' type.
>  There are types at '/workspaces/basic-bun/node_modules/@we-gold/gpxjs/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@we-gold/gpxjs' library may need to update its package.json or typings.

I'm using it with this import statement in my code.
```import { parseGPXWithCustomParser } from "@we-gold/gpxjs";```

The problem can be fixed by adding the following line to the `exports`-section in the package.json:
```diff
"exports": {
	".": {
		"import": "./dist/gpxjs.js",
		"require": "./dist/gpxjs.umd.cjs",
+		"types": "./dist/index.d.ts"
	}
},
```

If you have further questions, feel free to ask.

**Comment by We-Gold** [comment]
Thanks for letting me know. I pushed a new release (1.0.9) with the fix. Let me know if it doesn't resolve the issue.

**Comment by fabalexsie** [comment]
Thanks for the quick update. It is resolved.
