### ISSUE TITLE
feat: Support serialization back to GPX

### ISSUE THREAD

**Issue by bdferris-v2** [We-Gold/gpxjs#9]
It'd be great to have support for serializing the parsed GPX data model back to GPX XML.  Any chance you'd be willing to consider a PR that added this functionality?

**Comment by We-Gold** [comment]
That would be a desirable feature. I'm back in college for the year, so it's unlikely I could contribute to the PR, but I'd be glad to review and merge it. 

Edit: I may be able to work on it at some point, but I just don't know when that would be.
